title: Explainable and Responsible AI
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://gaberamolete.github.io/toolkit-xrai/

aux_links:
  Repository: https://github.com/gaberamolete/toolkit-xrai
